# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20170318_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
