# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_auto_20170318_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_token',
        ),
    ]
