# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0013_auto_20170320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='guest.user'),
        ),
    ]
